//! Lenovo battery HAL bridge backend.
//!
//! Proxies `vendor.lenovo.hardware.battery.IBattery/default` (AIDL V5, 53 vendor
//! methods). Like the Xiaomi HAL it is a plain AIDL NDK service on the binder
//! domain this process already uses, so no second transport is involved; the
//! interface was reconstructed from the shipped library (see
//! `chargehal-vendor-refs/lenovo/INTERFACE.md` for the transaction codes).
//!
//! Units follow `chargehal-vendor-refs/lenovo/NODES.md`: A = standard
//! `power_supply` ABI, used as-is; C = vendor-private, copied verbatim and never
//! scaled. No power field is filled: this HAL exposes no negotiated ("handshake")
//! power, and the delivered power is a different quantity that must not be
//! substituted for it.
//!
//! Charge control uses `setUsbSupplyDisabled`, which writes `usb/input_suspend`
//! with the value it is given. `setBatteryChargeDisabled` also exists but writes
//! the *inverted* value, so only one of the two may drive the same intent.

use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;

use parking_lot::Mutex;
use rsbinder::{hub, DeathRecipient, StatusCode, Strong, WIBinder};

use crate::adapter::ChargerInfo;

// Lenovo IBattery bindings, generated by build.rs from
// aidl/vendor/lenovo/hardware/battery/IBattery.aidl. They are included inside
// this module rather than at the library root because the generated file
// declares its own `vendor` module, which would collide with the Xiaomi one
// there. The interface is only ever used by this backend.
include!(concat!(env!("OUT_DIR"), "/lenovo_battery.rs"));
use self::vendor::lenovo::hardware::battery::IBattery::IBattery as LenovoBattery;

use super::sysfs::{self, SysfsBackend};
use super::ChargeBackend;

/// Service instance registered by the Lenovo battery HAL.
pub const LENOVO_SERVICE_NAME: &str = "vendor.lenovo.hardware.battery.IBattery/default";

/// Port index for the wired port (`usb/voltage_now`, `usb/current_now`).
///
/// Evidence: NODES.md §4 — `getPortxVoltageNow` branches `port == 1` to
/// `power_supply/usb/voltage_now` and `port == 2` to
/// `power_supply/wireless/voltage_now`.
const PORT_USB: i32 = 1;

/// Port index for the wireless rail (`wireless/voltage_now`, `wireless/current_now`).
const PORT_WIRELESS: i32 = 2;

/// Battery index for the main pack (`power_supply/battery/*`).
///
/// Evidence: NODES.md §4 — the `*ForNum` family branches `num == 1` to the main
/// pack and `num == 2` to `qcom-battery/fg2_*`.
const PACK_MAIN: i32 = 1;

/// Flips to `false` when the vendor HAL process dies.
struct LenovoDeath {
    alive: Arc<AtomicBool>,
}

impl DeathRecipient for LenovoDeath {
    fn binder_died(&self, _who: &WIBinder) {
        self.alive.store(false, Ordering::Release);
    }
}

/// Last cheap-probe result, compared against the next one.
#[derive(Clone, PartialEq, Eq, Default)]
struct ProbeSnapshot {
    initialized: bool,
    charger_type: String,
    port_voltage: i32,
    wireless_voltage: i32,
    ac_online: i32,
    wireless_online: i32,
}

struct HalProbeSample<'a> {
    charger_type: &'a str,
    port_voltage: Option<i32>,
    wireless_voltage: Option<i32>,
    ac_online: Option<i32>,
    wireless_online: Option<i32>,
}

/// Compare one cheap probe against the previous one.
///
/// The first sample always counts as a change. An unreadable node (`None`) does
/// not: a missing file must not look like the charger was unplugged and spin the
/// poll loop.
fn probe_sample_changed(cache: &mut ProbeSnapshot, sample: HalProbeSample<'_>) -> bool {
    let hal_changed = !cache.initialized
        || cache.charger_type != sample.charger_type
        || sample
            .port_voltage
            .is_some_and(|value| value != cache.port_voltage)
        || sample
            .wireless_voltage
            .is_some_and(|value| value != cache.wireless_voltage);
    let online_changed = cache.initialized
        && (sample
            .ac_online
            .is_some_and(|value| value != cache.ac_online)
            || sample
                .wireless_online
                .is_some_and(|value| value != cache.wireless_online));
    cache.initialized = true;
    cache.charger_type.clear();
    cache.charger_type.push_str(sample.charger_type);
    if let Some(value) = sample.port_voltage {
        cache.port_voltage = value;
    }
    if let Some(value) = sample.wireless_voltage {
        cache.wireless_voltage = value;
    }
    if let Some(value) = sample.ac_online {
        cache.ac_online = value;
    }
    if let Some(value) = sample.wireless_online {
        cache.wireless_online = value;
    }
    hal_changed || online_changed
}

/// Lenovo battery HAL backend.
pub struct LenovoBackend {
    service: Mutex<Option<Strong<dyn LenovoBattery>>>,
    alive: Arc<AtomicBool>,
    /// Kept alive for the lifetime of the link: `link_to_death` stores only a
    /// weak reference, so dropping this would silently disable death notices.
    death: Arc<LenovoDeath>,
    probe: Mutex<ProbeSnapshot>,
    fallback: SysfsBackend,
}

impl LenovoBackend {
    /// Connect to the vendor HAL.
    ///
    /// Fails when the service is not registered; the caller then falls back to
    /// the kernel-node reader.
    pub fn connect() -> Result<Self, StatusCode> {
        let alive = Arc::new(AtomicBool::new(true));
        let death = Arc::new(LenovoDeath {
            alive: Arc::clone(&alive),
        });
        let backend = Self {
            service: Mutex::new(None),
            alive,
            death,
            probe: Mutex::new(ProbeSnapshot::default()),
            fallback: SysfsBackend::new(),
        };
        backend.attach()?;
        Ok(backend)
    }

    /// Resolve the service and arm the death notification.
    fn attach(&self) -> Result<(), StatusCode> {
        let proxy = hub::check_interface::<dyn LenovoBattery>(LENOVO_SERVICE_NAME)?;
        if let Err(error) = proxy.link_to_death_arc(&self.death) {
            tracing::warn!("Lenovo battery death notification unavailable: {error}");
        }
        *self.service.lock() = Some(proxy);
        self.alive.store(true, Ordering::Release);
        Ok(())
    }

    /// Current proxy, reconnecting after a HAL restart.
    fn proxy(&self) -> Option<Strong<dyn LenovoBattery>> {
        #[cfg(not(target_os = "android"))]
        {
            None
        }
        #[cfg(target_os = "android")]
        {
            if self.alive.load(Ordering::Acquire) {
                if let Some(proxy) = self.service.lock().as_ref() {
                    return Some(proxy.clone());
                }
            }
            self.attach().ok()?;
            self.service.lock().clone()
        }
    }
}

impl ChargeBackend for LenovoBackend {
    fn name(&self) -> &'static str {
        "lenovo"
    }

    fn is_available(&self) -> bool {
        self.proxy().is_some()
    }

    fn refresh(&self, info: &mut ChargerInfo, should_cancel: &dyn Fn() -> bool) -> bool {
        if should_cancel() {
            return false;
        }
        let Some(proxy) = self.proxy() else {
            tracing::warn!("Lenovo battery HAL proxy unavailable; falling back to sysfs refresh");
            return self.fallback.refresh(info, should_cancel);
        };

        // ── Battery stage (A grade: units fixed by the power_supply ABI) ──
        apply_capacity(
            &mut info.battery_capacity,
            fetch(&*proxy, |p| p.getBatteryCapacity()),
        );
        apply_int(
            &mut info.battery_voltage_now,
            fetch(&*proxy, |p| p.getBatteryVoltage()),
        );
        apply_int(
            &mut info.battery_current_now,
            fetch(&*proxy, |p| p.getBatteryCurrent()),
        );
        apply_int(
            &mut info.battery_temp,
            fetch(&*proxy, |p| p.getBatteryTemperature()),
        );
        apply_int(
            &mut info.charge_full,
            fetch(&*proxy, |p| p.getBatteryChargeFull()),
        );
        apply_int(
            &mut info.charge_full_design,
            fetch(&*proxy, |p| p.getBatteryChargeFullDesign()),
        );
        apply_int(
            &mut info.charge_counter,
            fetch(&*proxy, |p| p.getBatteryChargeCounter()),
        );
        apply_int(
            &mut info.cycle_count,
            fetch(&*proxy, |p| p.getBatteryCycleCount()),
        );

        if should_cancel() {
            return false;
        }

        // ── Charger stage ──
        // `getChargerType` reads `usb/real_type` (C grade); `battery_charge_type`
        // matches where the Xiaomi backend puts its own charge-type getter.
        let charger_type = fetch(&*proxy, |p| p.getChargerType());
        // `getChargerType` reads `usb/real_type`, which is exactly the node the
        // fast-charge classifier reads first. Store it there as well, otherwise
        // this generation has no fast-charge input at all and everything reports
        // as plain charging. An unrecognised token simply falls through the
        // classifier, so an unconfirmed domain cannot produce a wrong verdict.
        apply_string(&mut info.usb_real_type, charger_type.clone());
        apply_string(&mut info.battery_charge_type, charger_type);
        // C grade: copied verbatim. The HAL substitutes 100 for negative reads,
        // so a plausible number can come from a failed read (NODES.md §7.3).
        apply_int(
            &mut info.fg_soh,
            fetch(&*proxy, |p| p.getBatterySOHForNum(PACK_MAIN)),
        );

        // No `usb_online` getter exists; derive it from port voltage, and only
        // update both together when the read parsed.
        if let Some(voltage) = fetch(&*proxy, |p| p.getPortxVoltageNow(PORT_USB)) {
            info.usb_voltage_now = voltage;
            info.usb_online = i32::from(voltage > 0);
        }
        apply_int(
            &mut info.usb_current_now,
            fetch(&*proxy, |p| p.getPortxCurrentNow(PORT_USB)),
        );
        // Wireless rail (A grade): same two quantities on the second port.
        apply_int(
            &mut info.wireless_voltage_now,
            fetch(&*proxy, |p| p.getPortxVoltageNow(PORT_WIRELESS)),
        );
        apply_int(
            &mut info.wireless_current_now,
            fetch(&*proxy, |p| p.getPortxCurrentNow(PORT_WIRELESS)),
        );
        apply_string(
            &mut info.fg_vendor,
            fetch(&*proxy, |p| p.getBatteryManufacturerForNum(PACK_MAIN)),
        );

        if should_cancel() {
            return false;
        }

        // ── Remaining time ──
        // The contract exposes this as `ttf_info`, i.e. time to full, so that is
        // the quantity to source. This generation reports time-to-*empty* even
        // while charging (measured: full=0, empty=29220 s at 96 % charging), so
        // using it would advertise a wrong time to full. The shared estimator,
        // which also computes time-to-full while charging, is the fallback.
        info.remaining_time = fetch(&*proxy, |p| p.getBatteryTimeToFullNow())
            .map(sysfs::clamp_i64_to_i32)
            .filter(|value| *value > 0)
            .unwrap_or(0);
        if info.remaining_time == 0 {
            info.remaining_time = sysfs::estimate_remaining_time_seconds(info);
        }

        // Authenticity is fixed, not sourced: see `ChargerInfo::authentic`.
        info.authentic = crate::adapter::AUTHENTIC_REPORTED;

        // ── Supplemental reads ──
        // Nodes the HAL exposes no getter for. `usb/input_suspend` is read back so
        // the reported state matches what the control path wrote; the inverted
        // `battery/charging_enable` is not read. `usb_type` stays empty: feeding
        // the adapter-type node into it would make `is_data_port_usb_type`
        // classify the charger as a computer.
        let batt_status_path = format!("{}/status", sysfs::PSY_BATTERY);
        let batt_health_path = format!("{}/health", sysfs::PSY_BATTERY);
        let ac_online_path = format!("{}/online", sysfs::PSY_AC);
        let wireless_online_path = format!("{}/online", sysfs::PSY_WIRELESS);
        let dc_online_path = format!("{}/online", sysfs::PSY_DC);
        let input_suspend_path = format!("{}/input_suspend", sysfs::PSY_USB);
        sysfs::update_non_empty_string_from_paths(&mut info.battery_status, &[&batt_status_path]);
        sysfs::update_non_empty_string_from_paths(&mut info.battery_health, &[&batt_health_path]);
        sysfs::update_int_from_paths(&mut info.ac_online, &[&ac_online_path]);
        sysfs::update_online_from_paths(
            &mut info.wireless_online,
            &[&wireless_online_path, &dc_online_path],
        );
        sysfs::update_int_from_paths(&mut info.input_suspend, &[&input_suspend_path]);
        sysfs::update_int_from_paths(&mut info.pc_port_online, sysfs::PC_PORT_ONLINE_PATHS);

        if should_cancel() {
            return false;
        }

        // Drop any stale generic "USB" left by an earlier scan; `usb_real_type`
        // is kept because it carries this generation's charger type.
        info.usb_type.clear();

        let charger_online =
            info.usb_online != 0 || info.ac_online != 0 || info.wireless_online != 0;
        if !charger_online {
            sysfs::clear_fast_charge_session(info);
        } else if sysfs::is_data_port(info) {
            // A computer is on the other end: drop stale fast-charge evidence.
            sysfs::suppress_fast_charge_evidence(info);
        }

        info.fast_charge_type = sysfs::classify_fast_charge(info);
        info.charge_technology = sysfs::classify_charge_technology(info);
        info.charge_state = sysfs::classify_charge_state(info);

        true
    }

    fn set_charge_control(&self, restrict: bool) {
        let Some(proxy) = self.proxy() else {
            tracing::warn!("Lenovo battery HAL unavailable; falling back to sysfs charge control");
            self.fallback.set_charge_control(restrict);
            return;
        };
        match fetch(&*proxy, |p| p.setUsbSupplyDisabled(restrict)) {
            // `false` is the HAL's "the write failed" flag, not an error.
            Some(true) => {}
            Some(false) => {
                tracing::warn!("Lenovo setUsbSupplyDisabled({restrict}) reported failure");
            }
            None => {
                // Transport failure: the call never reached the HAL.
                tracing::warn!(
                    "Lenovo setUsbSupplyDisabled({restrict}) failed; trying sysfs fallback"
                );
                self.fallback.set_charge_control(restrict);
            }
        }
    }

    fn set_charge_limit(&self, limit_percent: Option<i32>) {
        let Some(proxy) = self.proxy() else {
            return;
        };
        // The node is this generation's max-charging-level setting; 100 is sent
        // to release the limit. Its value domain is unconfirmed (NODES.md §7.1),
        // so the HAL can accept the write without the level meaning what we mean.
        let value = limit_percent.unwrap_or(100).clamp(0, 100);
        match fetch(&*proxy, |p| p.setMaxBatteryChargingLevel(value)) {
            Some(true) => {}
            Some(false) => {
                tracing::warn!("Lenovo setMaxBatteryChargingLevel({value}) reported failure");
            }
            None => {
                tracing::warn!("Lenovo setMaxBatteryChargingLevel({value}) failed");
            }
        }
    }

    fn set_bypass_charge(&self, enabled: bool) {
        let Some(proxy) = self.proxy() else {
            return;
        };
        // The HAL takes an int level; its value domain is unconfirmed, so this
        // sends the plain enable pair the vendor contract itself uses.
        let value = i32::from(enabled);
        match fetch(&*proxy, |p| p.setBypassLevel(value)) {
            Some(true) => {}
            Some(false) => {
                tracing::warn!("Lenovo setBypassLevel({value}) reported failure");
            }
            None => {
                tracing::warn!("Lenovo setBypassLevel({value}) failed");
            }
        }
    }

    fn charge_limit_percent(&self) -> Option<i32> {
        let proxy = self.proxy()?;
        fetch(&*proxy, |p| p.getMaxBatteryChargingLevel()).filter(|value| (0..=100).contains(value))
    }

    fn bypass_charge_enabled(&self) -> Option<bool> {
        let proxy = self.proxy()?;
        fetch(&*proxy, |p| p.getBypassLevel()).map(|level| level != 0)
    }

    fn power_source_changed(&self) -> bool {
        // Cheap probe only. Capacity is deliberately absent: it drifts upward
        // while charging and would escalate to a full scan every percent.
        let Some(proxy) = self.proxy() else {
            return self.fallback.power_source_changed();
        };
        let Some(charger_type) = fetch(&*proxy, |p| p.getChargerType()) else {
            // An unanswerable probe must escalate, not report "no change".
            return true;
        };

        let ac_online_path = format!("{}/online", sysfs::PSY_AC);
        let wireless_online_path = format!("{}/online", sysfs::PSY_WIRELESS);
        let dc_online_path = format!("{}/online", sysfs::PSY_DC);
        let sample = HalProbeSample {
            charger_type: &charger_type,
            port_voltage: fetch(&*proxy, |p| p.getPortxVoltageNow(PORT_USB)),
            wireless_voltage: fetch(&*proxy, |p| p.getPortxVoltageNow(2)),
            ac_online: sysfs::try_read_int(&ac_online_path),
            wireless_online: sysfs::try_read_online_any(&[&wireless_online_path, &dc_online_path]),
        };
        probe_sample_changed(&mut self.probe.lock(), sample)
    }
}

/// Run one HAL getter, logging and swallowing transport failures.
fn fetch<T>(
    proxy: &dyn LenovoBattery,
    call: impl FnOnce(&dyn LenovoBattery) -> rsbinder::BinderResult<T>,
) -> Option<T> {
    match call(proxy) {
        Ok(value) => Some(value),
        Err(error) => {
            tracing::debug!("Lenovo battery call failed: {error}");
            None
        }
    }
}

/// Overwrite `target` only when the HAL value parses; never clear on failure.
fn apply_int(target: &mut i32, raw: Option<i32>) {
    if let Some(value) = raw {
        *target = value;
    }
}

/// Percentage, tolerating the 0..10000 form some nodes use.
fn apply_capacity(target: &mut i32, raw: Option<i32>) {
    if let Some(value) = raw {
        *target = sysfs::normalize_battery_capacity(value);
    }
}

/// Overwrite `target` only with a non-empty trimmed string.
fn apply_string(target: &mut String, raw: Option<String>) {
    let Some(value) = raw else {
        return;
    };
    let value = value.trim();
    if !value.is_empty() {
        target.clear();
        target.push_str(value);
    }
}

#[cfg(test)]
mod tests {
    use super::{probe_sample_changed, HalProbeSample, ProbeSnapshot};

    fn sample<'a>(
        charger_type: &'a str,
        port_voltage: Option<i32>,
        ac_online: Option<i32>,
    ) -> HalProbeSample<'a> {
        HalProbeSample {
            charger_type,
            port_voltage,
            wireless_voltage: None,
            ac_online,
            wireless_online: None,
        }
    }

    #[test]
    fn first_sample_always_counts_as_a_change() {
        let mut cache = ProbeSnapshot::default();
        assert!(probe_sample_changed(
            &mut cache,
            sample("USB", Some(5_000_000), Some(1))
        ));
    }

    #[test]
    fn identical_samples_do_not_escalate() {
        let mut cache = ProbeSnapshot::default();
        probe_sample_changed(&mut cache, sample("USB", Some(5_000_000), Some(1)));
        assert!(!probe_sample_changed(
            &mut cache,
            sample("USB", Some(5_000_000), Some(1))
        ));
    }

    #[test]
    fn unreadable_online_node_is_not_a_change() {
        let mut cache = ProbeSnapshot::default();
        probe_sample_changed(&mut cache, sample("USB", Some(5_000_000), Some(1)));
        assert!(!probe_sample_changed(
            &mut cache,
            sample("USB", Some(5_000_000), None)
        ));
        // ...and the cached value must survive the unreadable sample.
        assert_eq!(cache.ac_online, 1);
    }

    #[test]
    fn a_plug_event_escalates() {
        let mut cache = ProbeSnapshot::default();
        probe_sample_changed(&mut cache, sample("USB", Some(0), Some(0)));
        assert!(probe_sample_changed(
            &mut cache,
            sample("USB", Some(5_000_000), Some(1))
        ));
    }
}
