pub mod adapter;
pub mod backend;

pub const SERVICE_NAME: &str = "vendor.oplus.hardware.charger.ICharger/default";
pub const INTERFACE_HASH: &str = "046dfc7a9ca30bfca848ced6e9474f47437b0db7";
pub const INTERFACE_VERSION: i32 = 11;

// Xiaomi MiCharge bindings, generated by build.rs from
// aidl/vendor/xiaomi/hardware/micharge/IMiCharge.aidl.
//
// They are included at the library root rather than in the binary so that the
// bridge backend in `backend::micharge` can reach them. The OPlus bindings stay
// in the binary because only the service implementation uses them.
include!(concat!(env!("OUT_DIR"), "/micharge.rs"));
